### ISSUE TITLE
Bug in Qt 5.9 port (and 5.8 as well) makes Scribus 1.5.3 crash

### ISSUE THREAD

**Issue by RobertoCMCosta** [haikuports/haikuports#1493]
I've been trying to use the latest version of Scribus (1.5.3), for which there's an official recipe now. The application builds and runs but crashes when trying to use any editing tool. It simply quits without notice. 
According to one of Scribus developers [here](https://bugs.scribus.net/view.php?id=14843), the problem lies in the Qt port code. (This forum entry has debug information that I sent the app developers)
The discussion in Haiku forum, where Miqlas and other devs helped me, can be found [here](https://discuss.haiku-os.org/t/cant-get-scribus-1-5-2-to-work/5697/41)

Scribus is a very useful DTP application that can produce press-ready and forms PDFs.
Haiku OS already has a working package of version 1.4.6 of the app. However getting the latest version to run would add a lot features that were packed into the app over the last years since that version was released including big performance improvements.
I wish you guys can find and fix this bug which may help other Qt apps run better in Haiku. 
Thank you.

**Comment by korli** [comment]
Relevant bug report at scribus.net:
https://bugs.scribus.net/view.php?id=14843

```
0x7fff447bc480	0x7ff83340923b	commpage_signal_handler + 0x2b 
0x7fff447bc890	0x103e9220940	QWidget::windowHandle() const + 0 
0x7fff447bc930	0x103e922d654	QWidgetPrivate::create_sys(unsigned long long, bool, bool) + 0x2e4 
0x7fff447bc9a0	0x103e922dbb4	QWidget::create(unsigned long long, bool, bool) + 0x114 
0x7fff447bca00	0x103e92384e9	QWidget::setVisible(bool) + 0x89 
0x7fff447bca50	0x103e921cb5e	QToolTip::showText(QPoint const&, QString const&, QWidget*, QRect const&, int) + 0x11e 
0x7fff447bca70	0x103e921cca8	QToolTip::showText(QPoint const&, QString const&, QWidget*) + 0x28 
0x7fff447bcb30	0x1a75c7fcd5f	Canvas::displayCorrectedXYHUD(QPoint, double, double) + 0x20b (/sources/scribus-1.5.3/scribus/canvas.cpp:-1)

**Comment by RobertoCMCosta** [comment]
Just note that the debug info above was taken from a build based on Qt 5.8. But I guess the same bug is present in the current Qt 5.9 codebase.

**Comment by threedeyes** [comment]
Fixed in 504b68d72ab3e1c101b0f0e149d3b0e780e38694

**Comment by miqlas** [comment]
Then somebody should revert this: https://github.com/haikuports/haikuports/commit/438ac799251e56b5c660c83b2f8d88e1948b57c7

**Comment by RobertoCMCosta** [comment]
In order to test it do I have to recompile Qt and Scribus?
I searched this plugin in my local haikuport and couldn't find it, only qthaikustyles.

**Comment by diversys** [comment]
`qthaikustyles` was replaced with `qthaikuplugins` and this is what you will need (no need to recompile Scribus AFAIK). You probably need to update your ports tree using `haikuporter -g`. 
However, it is currently fails to build (see haikuports#1540) unless you recompile Qt yourself first which takes 3-5 hours.

**Comment by RobertoCMCosta** [comment]
well diversys... it still doesn't work. 
I removed the old Qt package, installed and built Qt 5.9.1-3 from scratch (3 hours or more) then tried running the installed Scribus binary (1.5.3-1). I got an error of missing Qt plugin "haiku". So I uninstalled Scribus, refreshed the local haikuports tree, built it again and... bump! The program crashes right away. So it's a little worse now than before because I can't even see the program face anymore.
Attached the crash report
[Scribus-369-debug-18-08-2017-14-13-35.txt](https://github.com/haikuports/haikuports/files/1235140/Scribus-369-debug-18-08-2017-14-13-35.txt)

**Comment by threedeyes** [comment]
Which version of qthaikuplugins is installed?

**Comment by RobertoCMCosta** [comment]
sorry for the delay. Did you mean Qthaikustyle? If so, it's version 1.0˜git-1 that was installed together with Qt 5 mentioned in my last post.

**Comment by diversys** [comment]
As I said qthaikustyles was replaced with qthaikuplugins and this is what you need to build yourself using haikuporter.

**Comment by RobertoCMCosta** [comment]
My bad!
I've just built it and it replaced Qthaikustyles after installing the new package. Scribus continues to crash at startup. 
Is there anything else I'm missing?
